apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vprd
spec:
  interval: 1m
  chart:
    spec:
      chart: ci-cd-demo
      version: '0.1.1'
      sourceRef:
        kind: HelmRepository
        name: ghcr.io-danielr1996
        namespace: flux-system
      interval: 1m
  values:
    frontend:
      backendUrl: https://backend.vprd.demo.danielrichter.codes
      image:
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: frontend.vprd.demo.danielrichter.codes
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: frontend.vprd.demo.danielrichter.codes
            hosts:
              - frontend.vprd.demo.danielrichter.codes
    backend:
      image:
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: backend.vprd.demo.danielrichter.codes
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: backend.vprd.demo.danielrichter.codes
            hosts:
              - backend.vprd.demo.danielrichter.codes