apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sit
spec:
  interval: 1m
  chart:
    spec:
      chart: ci-cd-demo
      version: '0.2.0' # {"$imagepolicy": "ci-cd-demo:latest-stable:tag"}
      sourceRef:
        kind: HelmRepository
        name: ghcr.io-danielr1996
        namespace: flux-system
      interval: 1m
  values:
    frontend:
      backendUrl: https://backend.sit.demo.danielrichter.codes
      image:
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: frontend.sit.demo.danielrichter.codes
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: frontend.sit.demo.danielrichter.codes
            hosts:
              - frontend.sit.demo.danielrichter.codes
    backend:
      environment: SIT
      image:
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: backend.sit.demo.danielrichter.codes
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: backend.sit.demo.danielrichter.codes
            hosts:
              - backend.sit.demo.danielrichter.codes
